# Time-stamp: <03/07/15 17:54:22 ptr>
# $Id$

PRG        := $(OUTPUT_DIR)/${PRGNAME}_r${LIBMAJOR}${LIBMINOR}${EXE}
PRG_DBG    := $(OUTPUT_DIR)/${PRGNAME}_d${LIBMAJOR}${LIBMINOR}${EXE}
PRG_STLDBG := $(OUTPUT_DIR)/${PRGNAME}_stld${LIBMAJOR}${LIBMINOR}${EXE}

LDFLAGS += ${LDSEARCH}
