# -*- Makefile -*- Time-stamp: <04/03/31 08:14:15 ptr>
# $Id$

SRCROOT=../../src/explore
STLPORT_DIR=../..

!include Makefile.inc

INCLUDES=$(INCLUDES) /I "$(STLPORT_INCLUDE_DIR)" /I "cppunit" /I "$(STLPORT_DIR)/src/" /FI "vc_warning_disable.h"
DEFS = /DCPPUNIT_MINI=1
DEFS_DBG = /D_STLP_USE_DEBUG_LIB

DEFS_REL = /D_STLP_USE_DYNAMIC_LIB
DEFS_DBG = /D_STLP_USE_DYNAMIC_LIB
DEFS_STLDBG = /D_STLP_USE_DYNAMIC_LIB
DEFS_STATIC_REL = /D_STLP_USE_STATIC_LIB
DEFS_STATIC_DBG = /D_STLP_USE_STATIC_LIB
DEFS_STATIC_STLDBG = /D_STLP_USE_STATIC_LIB

LDSEARCH=$(LDSEARCH) /LIBPATH:$(STLPORT_LIB_DIR)

LDLIBS_REL=stlport_$(COMPILER_NAME).lib
LDLIBS_DBG=stlport_$(COMPILER_NAME)_debug.lib
LDLIBS_STLDBG=stlport_$(COMPILER_NAME)_stldebug.lib

LDLIBS_A_REL=stlport_$(COMPILER_NAME)_static.lib
LDLIBS_A_DBG=stlport_$(COMPILER_NAME)_debug_static.lib
LDLIBS_A_STLDBG=stlport_$(COMPILER_NAME)_stldebug_static.lib

!include $(SRCROOT)/Makefiles/nmake/top.mak
