# -*- Makefile -*- Time-stamp: <04/03/30 14:53:15 ptr>
# $Id$

SRCROOT=../../src/explore
STLPORT_DIR=../..

!include Makefile.inc

INCLUDES=$(INCLUDES) /I "$(STLPORT_INCLUDE_DIR)" /I "$(STLPORT_DIR)/src" /FI "vc_warning_disable.h"

!ifdef STLP_BUILD_BOOST_PATH
INCLUDES=$(INCLUDES) /I "$(STLP_BUILD_BOOST_PATH)"
!endif

DEFS = /D_STLP_NO_CUSTOM_IO /DCPPUNIT_MINI=1

LDSEARCH=$(LDSEARCH) /LIBPATH:$(STLPORT_LIB_DIR)

LDLIBS_REL=stlport_$(RELEASE_SUFFIX)$(LIBMAJOR)$(LIBMINOR).lib
LDLIBS_DBG=stlport_$(DBG_SUFFIX)$(LIBMAJOR)$(LIBMINOR).lib
LDLIBS_STLDBG=stlport_$(STLDBG_SUFFIX)$(LIBMAJOR)$(LIBMINOR).lib

LDLIBS_A_REL=stlport_static_$(RELEASE_SUFFIX)$(LIBMAJOR)$(LIBMINOR).lib
LDLIBS_A_DBG=stlport_static_$(DBG_SUFFIX)$(LIBMAJOR)$(LIBMINOR).lib
LDLIBS_A_STLDBG=stlport_static_$(STLDBG_SUFFIX)$(LIBMAJOR)$(LIBMINOR).lib

!include $(SRCROOT)/Makefiles/nmake/top.mak
